apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-predictor
  labels:
    app: health-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-predictor
  template:
    metadata:
      labels:
        app: health-predictor
    spec:
      containers:
      - name: flask-api
        image: health-predictor:v1
        imagePullPolicy: Never  # Use local image (for minikube)
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
