apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-predictor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-predictor
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 mins before scaling down
    scaleUp:
      stabilizationWindowSeconds: 0    # Scale up immediately
